In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
df = pd.read_csv(
    "../data/ecommerce_data_clean.csv"
)

df.head()

   order_date product_name     category region  quantity  sales  profit
0  2024-12-31      Printer       Office  North         4   3640  348.93
1  2022-11-27        Mouse  Accessories   East         7   1197  106.53
2  2022-05-11       Tablet  Electronics  South         5   5865  502.73
3  2024-03-16        Mouse  Accessories  South         2    786  202.87
4  2022-09-10        Mouse  Accessories   West         1    509  103.28

In [3]:
username = "postgres"
password = "Abi_28102000"
host = "localhost"
port = "5432"
database = "ecommerce_sales"

engine = create_engine(
    f"postgresql://{username}:{password}@{host}:{port}/{database}"
)

In [4]:
engine.connect()

In [5]:
df.to_sql(
    "ecommerce_sales",
    engine,
    if_exists="replace",
    index=False
)

500

In [6]:
#verivikasi data
query = """
SELECT COUNT(*)
FROM ecommerce_sales
"""

pd.read_sql(query, engine)

   count
0   3500

In [7]:
#Cek SQL sudah bisa berjalan atau belum
query = """
SELECT
    category,
    SUM(sales) revenue
FROM ecommerce_sales
GROUP BY category
ORDER BY revenue DESC
"""

pd.read_sql(query, engine)

      category    revenue
0  Electronics  5326074.0
1  Accessories  4247591.0
2       Office  1094216.0